"""empty message

Revision ID: bfc0073e59ea
Revises: 9651cf5742ad
Create Date: 2024-01-17 17:06:54.915755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc0073e59ea'
down_revision = '9651cf5742ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('monthly_budget', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'monthly_budget')
    # ### end Alembic commands ###
